/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Updated to point to your Supabase project
export const projectId = "wwodgnqzvvuzsdcjxrqi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3b2RnbnF6dnZ1enNkY2p4cnFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODA5ODAsImV4cCI6MjA3MzA1Njk4MH0.CGvjLLacZjAH6ioA_ciKSujk68153aN8Iq9A2GesS2U"
// Optional publishable key (provided) — exported for future use
export const publishableKey = "sb_publishable_7pcuz9lzNyEIiBJn4kXOlA_uArtZs8n"
