/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_6d448e25 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/wwodgnqzvvuzsdcjxrqi/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
// Note: we dynamically import the Supabase client only when SUPABASE env vars are present.

// Deno's global may not be present in other toolchains; declare to keep TS happy at edit time.
declare const Deno: any;

// Read Supabase env vars. If missing, we fall back to a simple in-memory Map
// so the backend can be run locally without requiring a Supabase project.
const SUPABASE_URL = typeof Deno !== 'undefined' ? Deno.env.get("SUPABASE_URL") : undefined;
const SUPABASE_KEY = typeof Deno !== 'undefined' ? Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") : undefined;

const useInMemory = !(SUPABASE_URL && SUPABASE_KEY);

let _supabaseClient: any = null;
const getSupabaseClient = async () => {
  if (_supabaseClient) return _supabaseClient;
  // dynamic import so Deno doesn't attempt to evaluate/create the client when env vars are missing
  const mod = await import('npm:@supabase/supabase-js@2.49.8');
  _supabaseClient = mod.createClient(SUPABASE_URL!, SUPABASE_KEY!);
  return _supabaseClient;
};

// In-memory store used as fallback for local development.
const store = new Map<string, any>();

export const set = async (key: string, value: any): Promise<void> => {
  if (!useInMemory) {
    const supabase = await getSupabaseClient();
    const { error } = await supabase.from("kv_store_6d448e25").upsert({ key, value });
    if (error) throw new Error(error.message);
    return;
  }
  store.set(key, value);
};

export const get = async (key: string): Promise<any> => {
  if (!useInMemory) {
    const supabase = await getSupabaseClient();
    const { data, error } = await supabase.from("kv_store_6d448e25").select("value").eq("key", key).maybeSingle();
    if (error) throw new Error(error.message);
    return data?.value;
  }
  return store.get(key) ?? null;
};

export const del = async (key: string): Promise<void> => {
  if (!useInMemory) {
    const supabase = await getSupabaseClient();
    const { error } = await supabase.from("kv_store_6d448e25").delete().eq("key", key);
    if (error) throw new Error(error.message);
    return;
  }
  store.delete(key);
};

export const mset = async (keys: string[], values: any[]): Promise<void> => {
  if (!useInMemory) {
    const supabase = await getSupabaseClient();
    const { error } = await supabase.from("kv_store_6d448e25").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
    if (error) throw new Error(error.message);
    return;
  }
  keys.forEach((k, i) => store.set(k, values[i]));
};

export const mget = async (keys: string[]): Promise<any[]> => {
  if (!useInMemory) {
    const supabase = await getSupabaseClient();
    const { data, error } = await supabase.from("kv_store_6d448e25").select("value").in("key", keys);
    if (error) throw new Error(error.message);
    return data?.map((d: any) => d.value) ?? [];
  }
  return keys.map(k => store.get(k) ?? null);
};

export const mdel = async (keys: string[]): Promise<void> => {
  if (!useInMemory) {
    const supabase = await getSupabaseClient();
    const { error } = await supabase.from("kv_store_6d448e25").delete().in("key", keys);
    if (error) throw new Error(error.message);
    return;
  }
  keys.forEach(k => store.delete(k));
};

export const getByPrefix = async (prefix: string): Promise<any[]> => {
  if (!useInMemory) {
    const supabase = await getSupabaseClient();
    const { data, error } = await supabase.from("kv_store_6d448e25").select("key, value").like("key", prefix + "%");
    if (error) throw new Error(error.message);
    return data?.map((d: any) => d.value) ?? [];
  }
  const results: any[] = [];
  for (const [k, v] of store.entries()) {
    if (k.startsWith(prefix)) results.push(v);
  }
  return results;
};